CREATE TABLE users
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    surname         VARCHAR(40) NOT NULL,
    name            VARCHAR(20) NOT NULL,
    patronymic_name VARCHAR(40) NULL,
    role            VARCHAR(30) NOT NULL
);