DROP TABLE IF EXISTS users;

CREATE TABLE users
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    surname         VARCHAR(40) NOT NULL,
    name            VARCHAR(20) NOT NULL,
    patronymic_name VARCHAR(40) NULL,
    role            VARCHAR(30) NOT NULL,
    email           VARCHAR(50) UNIQUE

);

INSERT INTO users (surname, name, patronymic_name, role, email)
VALUES ('Ivanov', 'Ivan', 'Ivanovich', ' SALE_USER', 'ivanov@gmail.com'),
       ('Petrov', 'Petr', 'Petrovich', 'ADMINISTRATOR', 'petrov@gmail.com'),
       ('Vasiliev', 'Vasilii', 'Vasilievich', 'CUSTOMER_USER', 'vasiliev@gmail.com'),
       ('Sergeev', 'Sergey', 'Sergeevich', 'SECURE_API_USER', 'sergeev@gmail.com'),
       ('Alexeev', 'Alexey', 'Alexeevich', 'SALE_USER', 'alexeev@gmail.com'),
       ('Mihailov', 'Mihail', 'Mihailovich', 'ADMINISTRATOR', 'mihailov@gmail.com'),
       ('Nikolaev', 'Nikolai', 'Nikolaevich', 'SECURE_API_USER', 'nikolaev@gmail.com');